[variables]
NIXPACKS_NO_MISE = "1"

[phases.setup]
nixPkgs = ["python312", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  # Build and cache your flake environment
  "nix develop -c true"
]


[start]
cmd = "python manage.py migrate && gunicorn windborne_application.wsgi --bind 0.0.0.0:$PORT"
