"""
Django settings for windborneApplication project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

################################
######################### N2YO
################################

N2YO_API_KEY = config("N2YO_API_KEY", default="")
# Observer location, required by N2YO:
N2YO_OBSERVER = {
    "lat": 37.7749,     # San Francisco
    "lon": -122.4194,
    "alt_km": 0.015     # ~15 m
}
# The satellites to plot, keep small to preserver API limits
SATELLITES = [
    {"id": 54234, "name": "NOAA-21 (JPSS-2)"},
    {"id": 43013, "name": "NOAA 20 (JPSS 1)"},
    {"id": 37849, "name": "SUOMI NPP"},
    {"id": 33591, "name": "NOAA 19"},
    {"id": 28654, "name": "NOAA 18"},
    {"id": 27453, "name": "NOAA 17"},
    {"id": 26536, "name": "NOAA 16"},
    {"id": 25338, "name": "NOAA 15"},
    {"id": 23455, "name": "NOAA 14"},
    {"id": 22739, "name": "NOAA 13"},
    {"id": 21263, "name": "NOAA 12"},
    {"id": 19531, "name": "NOAA 11"},
    {"id": 16969, "name": "NOAA 10"},
    {"id": 15427, "name": "NOAA 9"},
    {"id": 13923, "name": "NOAA 8"},
    {"id": 12553, "name": "NOAA 7"},
    {"id": 11416, "name": "NOAA 6"},
    {"id": 11060, "name": "TIROS N"},
    {"id": 9057,  "name": "NOAA 5"},
    {"id": 7529,  "name": "NOAA 4"},
    {"id": 6920,  "name": "NOAA 3"},
    {"id": 6235,  "name": "NOAA 2 (ITOS-D)"},
    {"id": 4793,  "name": "NOAA 1"},
]
# How many seconds of positions to request (1 = single current point)
N2YO_SECONDS = 1

###############################

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'windborne-applicaiton-production.up.railway.app',
    '127.0.0.1',
    'localhost',
] # Required by Railway

# Database configuration, should end up not using the database at all
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
    }
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "windborneApplication.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "windborneApplication.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
